### ISSUE TITLE
你好，我只看到draco下面有GetOrDecode解码函数，请问创建压缩函数在哪呢，似乎是没有提供，可否提供下呢，谢谢

### ISSUE THREAD

**Issue by 714865387** [code4game/libgltf#11]
你好，我只看到draco下面有GetOrDecode解码函数，请问创建压缩函数在哪呢，似乎是没有提供，可否提供下呢，谢谢

**Comment by 714865387** [comment]
因为我现在的需求是要将gltf使用draco压缩处理

**Comment by jixingcn** [comment]
这个库的目的是为了读取和解析gltf文件，所以并不需要压缩函数。
