### ISSUE TITLE
Problem with glb images

### ISSUE THREAD

**Issue by kveale** [code4game/libgltf#6]
I'm using libgltf in a game engine, and I noticed that the textures were not loading correctly when using a glb file. I tracked the problem down to the LoadByUri() function, where in the case of glb, it was just returning the whole binary chunk. I changed the code so that LoadByUri() uses the image's buffer view offset and size to point to the correct PNG data inside the chunk. Would you be interested in this code change?

**Comment by jixingcn** [comment]
Yes, I am interested. Could you share your commitment?
Sorry for the late reaction.

**Comment by kveale** [comment]
No problem. Could be a couple days.

**Comment by jixingcn** [comment]
Thanks a lot.:clap:
And I fix it in b81a7fa35001498b3184c2074be76dce8fed90a2.

You can try the latest in your project.:blush:

**Comment by kveale** [comment]
i will try it soon. thanks!
